#define TK_DIRE								"Directiva_de_Processamento"
#define TK_PRV								"Palavra_Reservada"
#define TK_ID								"identificador"
#define TK_CM 								"comentario"
#define TK_TEXT                             "Texto"

#define TK_AP 								"abre_parenteses"
#define TK_FP 								"fecha_parenteses"

#define TK_AC 								"abre_chaves"
#define TK_FC 								"fecha_chaves"

#define TK_INI 								"Inicio_arquivo"
#define TK_END 								"final_arquivo"
#define TK_PV 								"ponto_virgula"
#define TK_VG 								"virgula"

#define TK_AD 								"adicao"
#define TK_SUB 								"subtracao"
#define TK_MUL 								"multiplicacao"
#define TK_DIV 								"divisao"
#define TK_MOD 								"modulo"

#define TK_MENOR 							"menor"
#define TK_MAIOR 							"maior"
#define TK_MENORIG 							"menor_igual"
#define TK_MAIORIG 							"maior_igual"
#define TK_IG 								"igual"
#define TK_DIF 								"diferente"

#define TK_AND 								"E_logico"
#define TK_OR 								"OU_logico"
#define TK_NEG 								"negacao"

#define TK_DES_ES				    		"Deslocamento a Esquerda"
#define TK_DES_D	    					"Deslocamento a Direita"
#define TK_BOU_EX		    				"OPerador Bitwise OU exclusivo"
#define TK_BE		        				"Operador Bitwise E"
#define TK_BOU  			    			"Operador Bitwise OU"
#define TK_BCOMP  			    			"Operador Complemento Bitwise"

#define TK_INT 								"int"
#define TK_FLOAT 							"float"
#define TK_CHAR 							"char"
#define TK_DOUBLE 							"double"

#define TK_INCREMENT 						"Incremento"
#define TK_DECREMENT 						"Decremento"
#define TK_ATR								"Atribuicao Simples"
#define TK_ATR_AD							"Adicao e Atribuicao"
#define TK_ATR_SUB							"Subtra��o e Atribuicao"
#define TK_ATR_MUL							"Multiplica��o e Atribuicao"
#define TK_ATR_DIV							"DIV e Atribuicao"
#define TK_ATR_MOD							"M�dulo e Atribuicao"
#define TK_ATR_DES_ES						"Deslocamento a Esquerda e Atribuicao"
#define TK_ATR_DES_D						"Deslocamento a Direita e Atribuicao"
#define TK_ATR_BOU_EX		    				"OPerador Bitwise OU exclusivo e atribuicao"
#define TK_ATR_BE		        				"Operador Bitwise E e Atribuicao"
#define TK_ATR_BOU  			    			"Operador Bitwise OU e Atribuicao"

#define TK_ADDRESS						    "Endereço"
#define TK_POINTER						"Ponteiro"